### ISSUE TITLE
[change] Move Python dependencies to requirements.txt 

### ISSUE THREAD

**Issue by pandafy** [openwisp/ansible-wireguard-openwisp#52]
Move Python dependencies from pip.yml to a requirements.txt file. 

Ensure that dependabot can upgrade the dependencies in requirements.txt.

**Comment by pandafy** [comment]
We can use the following tasks to implement this 

```yml
- name: Read local requirements.txt and install packages
  local_action: command cat /path/to/requirements.txt
  register: requirements

- name: Install Python modules from requirements.txt
  pip:
    name: "{{ requirements.stdout_lines }}"
    state: present
  become: yes

```
